version: 2
registries:
  public-npm:
    type: npm-registry
    url: https://registry.npmjs.org
    # This forces Dependabot to treat this registry as the global base
    replaces-base: true
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    exclude-paths:
      - '.github/workflows/*'
      - '.github/actions/**'
    schedule:
      # interval: "monthly"
      # day: "friday"
      # interval: 'daily'
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
      include: 'scope' # Automatically appends "(deps)" -> ci(deps):
    labels: ['dependencies', 'deps:github-actions']
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
    assignees: ['andrewhaller']
  - package-ecosystem: 'github-actions'
    directories:
      - '.github/workflows'
      - '.github/actions/**'
    schedule:
      # interval: "monthly"
      # day: "friday"
      # interval: 'daily'
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope' # Automatically appends "(deps)" -> ci(deps):
    labels: ['dependencies', 'deps:github-actions']
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
    assignees: ['andrewhaller']
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      # interval: "monthly"
      # day: "friday"
      # interval: 'daily'
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        # update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      include: 'scope' # Automatically appends "(deps)" -> chore(deps):
    labels: ['dependencies', 'deps:javascript']
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - '*'
    assignees: ['andrewhaller']
    registries:
      - public-npm
