name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    # with:
    #   dispatch-workflow: publish.yaml
    secrets:
      github-token: ${{ secrets.GH_PAT_CREATE_RELEASE }}
