name: Update packages

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: '${{ github.repository_id }}-${{ github.ref_name }}'
  cancel-in-progress: false

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  package-update:
    name: Update packages
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Publish workflow
        if: ${{ (github.event.head_commit.author.name != 'semantic-release-bot' && github.event.head_commit.author.name != 'github-actions[bot]') && !startsWith(github.event.head_commit.message, 'chore(release):') }}
        uses: stairwaytowonderland/simple-workflow-dispatch@main
        with:
          workflow: ci.yaml
