name: Pre-commit

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      config:
        description: 'Path to the pre-commit config file.'
        type: string
        default: '.pre-commit-config.yaml'

  workflow_call:
    inputs:
      config:
        description: 'Path to the pre-commit config file.'
        type: string
        default: '.pre-commit-config.yaml'

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    name: Run pre-commit
    uses: stairwaytowonderland/.github/.github/workflows/pre-commit.yaml@v1
    with:
      config: ${{ inputs.config || '.pre-commit-config.yaml' }}
